spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chatbot_db?serverTimezone=Asia/Seoul
    username: root
    password: 772100kk
    driver-class-name: com.mysql.cj.jdbc.Driver
  ai:
    google:
      genai:
        api-key: 
        chat:
          options:
            model: gemini-2.5-flash-lite